[phases.setup]
nixPkgs = ["nodejs-18_x", "ffmpeg-full", "yt-dlp"]

[phases.install]
cmds = [
  "npm ci --omit=dev --omit=optional"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start" 