[phases.setup]
nixPkgs = ["nodejs-24_x", "ffmpeg-full", "yt-dlp", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "npm ci --omit=dev --omit=optional"
]

[phases.build]
cmds = [
  "npm install --no-save --platform=linuxmusl --arch=x64 lightningcss",
  "npm run build"
]

[variables]
NPM_CONFIG_PLATFORM = "linux"
NPM_CONFIG_ARCH = "x64"

[start]
cmd = "npm start" 